name: Token Exchange
description: A plugin to perform RFC 6749 token exchange
author: Equinix Metal
requirements:
  - bash
  - curl
  - uname
  - buildkite-agent
configuration:
  properties:
    token-endpoint:
      type: string
      description: "URL of the authorization server's token endpoint"
    buildkite-audience:
      type: string
      description: "Audience for Buildkite OIDC token"
      default: identity-api
    debug:
      type: boolean
      description: "Enable debug mode"
      default: false
  additionalProperties: false
